INSERT INTO bookIndex (address,name) VALUES ('/Users/glw/Downloads/众筹电子书/众筹电子书','.DS_Store');
INSERT INTO bookIndex (address,name) VALUES ('/Users/glw/Downloads/众筹电子书/众筹电子书','Spring Cloud与Docker微服务架构实战（带目录） .pdf');
INSERT INTO bookIndex (address,name) VALUES ('/Users/glw/Downloads/众筹电子书/众筹电子书','《Spring Cloud与Docker微服务架构实战》.pdf');
INSERT INTO bookIndex (address,name) VALUES ('/Users/glw/Downloads/众筹电子书/众筹电子书','《Spring Cloud微服务实战》.pdf');
INSERT INTO bookIndex (address,name) VALUES ('/Users/glw/Downloads/众筹电子书/众筹电子书','Spring Cloud微服务实战(（带目录）.pdf');
INSERT INTO bookIndex (address,name) VALUES ('/Users/glw/Downloads/众筹电子书/众筹电子书/第I期','《大数据搜索与日志挖掘及可视化方案ELKStack-Elasticsearch-Logstash-Kibana(第2版)》.pdf');
INSERT INTO bookIndex (address,name) VALUES ('/Users/glw/Downloads/众筹电子书/众筹电子书/第I期','《零基础学大数据算法》.pdf');
INSERT INTO bookIndex (address,name) VALUES ('/Users/glw/Downloads/众筹电子书/众筹电子书/第C期','《Hadoop大数据开发案例教程与项目实战》.pdf');
INSERT INTO bookIndex (address,name) VALUES ('/Users/glw/Downloads/众筹电子书/众筹电子书/第C期','《深入React技术栈》.pdf');
INSERT INTO bookIndex (address,name) VALUES ('/Users/glw/Downloads/众筹电子书/众筹电子书/第B4期','《机器人Python极客编程入门与实战》.pdf');
INSERT INTO bookIndex (address,name) VALUES ('/Users/glw/Downloads/众筹电子书/众筹电子书/第J期','《iOS10快速开发：18天零基础开发一个商业应用》.pdf');
INSERT INTO bookIndex (address,name) VALUES ('/Users/glw/Downloads/众筹电子书/众筹电子书/第J期','《第一行代码 JAVA 视频讲解版》.pdf');
INSERT INTO bookIndex (address,name) VALUES ('/Users/glw/Downloads/众筹电子书/众筹电子书/第J期','《Ansible快速入门：技术原理与实战》.pdf');
INSERT INTO bookIndex (address,name) VALUES ('/Users/glw/Downloads/众筹电子书/众筹电子书/第J期','《PaaS实现与运维管理：基于Mesos +Docker+ELK的实战指南》.pdf');
INSERT INTO bookIndex (address,name) VALUES ('/Users/glw/Downloads/众筹电子书/众筹电子书/第E8期（2018-12-4）','《从零开始自己动手写区块链》_裴尧尧_2018-11-12.pdf');
INSERT INTO bookIndex (address,name) VALUES ('/Users/glw/Downloads/众筹电子书/众筹电子书/第E8期（2018-12-4）','《Elasticsearch源码解析与优化实战》_张超_2018-11-01.pdf');
INSERT INTO bookIndex (address,name) VALUES ('/Users/glw/Downloads/众筹电子书/众筹电子书/第E8期（2018-12-4）','《Netty进阶之路 跟着案例学Netty》_李林锋_2018-11-01.pdf');
INSERT INTO bookIndex (address,name) VALUES ('/Users/glw/Downloads/众筹电子书/众筹电子书/第F9期（2019-02-19）','《Docker容器技术与应用》_朱晓彦等_2017-12-01.pdf');
INSERT INTO bookIndex (address,name) VALUES ('/Users/glw/Downloads/众筹电子书/众筹电子书/第F9期（2019-02-19）','《深入浅出Istio：Service Mesh快速入门与实践》_崔秀龙_2019-01-01.pdf');
INSERT INTO bookIndex (address,name) VALUES ('/Users/glw/Downloads/众筹电子书/众筹电子书/第A9期','《DevOps开发运维训练营》.pdf');
INSERT INTO bookIndex (address,name) VALUES ('/Users/glw/Downloads/众筹电子书/众筹电子书/第C10期（2018-07-31）','《Python文本分析》_闫龙川,高德荃,李君婷译.pdf');
INSERT INTO bookIndex (address,name) VALUES ('/Users/glw/Downloads/众筹电子书/众筹电子书/第F2期（2019-01-01）','《疯狂Python讲义》_李刚_2019-01-01.pdf');
INSERT INTO bookIndex (address,name) VALUES ('/Users/glw/Downloads/众筹电子书/众筹电子书/第U期','《精通Git（第2版）》.pdf');
INSERT INTO bookIndex (address,name) VALUES ('/Users/glw/Downloads/众筹电子书/众筹电子书/第U期','《构建实时机器学习系统》.pdf');
INSERT INTO bookIndex (address,name) VALUES ('/Users/glw/Downloads/众筹电子书/众筹电子书/第D8期（2018-09-25）','《JavaScript函数式编程指南》_欧阳继超等译.pdf');
INSERT INTO bookIndex (address,name) VALUES ('/Users/glw/Downloads/众筹电子书/众筹电子书/第V期','《ES6标准入门（第3版）》.pdf');
INSERT INTO bookIndex (address,name) VALUES ('/Users/glw/Downloads/众筹电子书/众筹电子书/第N期','《微信小程序开发入门与实践》.pdf');
INSERT INTO bookIndex (address,name) VALUES ('/Users/glw/Downloads/众筹电子书/众筹电子书/第N期','《Cloud Native Go：构建基于Go和React的云原生Web应用与微服务》.pdf');
INSERT INTO bookIndex (address,name) VALUES ('/Users/glw/Downloads/众筹电子书/众筹电子书/第M期','《MEAN Web开发》.pdf');
INSERT INTO bookIndex (address,name) VALUES ('/Users/glw/Downloads/众筹电子书/众筹电子书/第F3期（2019-01-08）','《基于Python的大数据分析基础及实战》_余本国_2018-07-01.pdf');
INSERT INTO bookIndex (address,name) VALUES ('/Users/glw/Downloads/众筹电子书/众筹电子书/第F3期（2019-01-08）','《HTML5布局之路》_刘国利_2017-5-17.pdf');
INSERT INTO bookIndex (address,name) VALUES ('/Users/glw/Downloads/众筹电子书/众筹电子书/第G2期（2019-03-10）','《实时大数据分析基于Storm、Spark技术的实时应用》_张广骏译_2018-01-01.pdf');
INSERT INTO bookIndex (address,name) VALUES ('/Users/glw/Downloads/众筹电子书/众筹电子书/第G2期（2019-03-10）','《疯狂Android讲义（Kotlin版）》_李刚_2018-06-01.pdf');
INSERT INTO bookIndex (address,name) VALUES ('/Users/glw/Downloads/众筹电子书/众筹电子书/第F期','《Mybatis从入门到精通》.pdf');
INSERT INTO bookIndex (address,name) VALUES ('/Users/glw/Downloads/众筹电子书/众筹电子书/第F期','《深入理解JVM ＆ G1 GC 》.pdf');
INSERT INTO bookIndex (address,name) VALUES ('/Users/glw/Downloads/众筹电子书/众筹电子书/第F期','《开源容器云OpenShift：构建基于Kuberes的企业应用云平台》.pdf');
INSERT INTO bookIndex (address,name) VALUES ('/Users/glw/Downloads/众筹电子书/众筹电子书/第F期','《Node.js实战 in action中文版》.pdf');
INSERT INTO bookIndex (address,name) VALUES ('/Users/glw/Downloads/众筹电子书/众筹电子书/第O期','《Jasper Reports+iReport报表开发详解》.pdf');
INSERT INTO bookIndex (address,name) VALUES ('/Users/glw/Downloads/众筹电子书/众筹电子书/第E期','《Ionic实战：基于AngularJS的移动混合应用开发》.pdf');
INSERT INTO bookIndex (address,name) VALUES ('/Users/glw/Downloads/众筹电子书/众筹电子书/第E期','《企业大数据系统构建实战：技术、架构、实施与应用》.pdf');
INSERT INTO bookIndex (address,name) VALUES ('/Users/glw/Downloads/众筹电子书/众筹电子书/第E期','《没什么难的Docker入门与开发实战》.pdf');
INSERT INTO bookIndex (address,name) VALUES ('/Users/glw/Downloads/众筹电子书/众筹电子书/第E期','《网络爬虫全解析――技术、原理与实践-java版》.pdf');
INSERT INTO bookIndex (address,name) VALUES ('/Users/glw/Downloads/众筹电子书/众筹电子书/第D1期（2018-08-07）','《RocketMQ实战与原理解析》_杨开元.pdf');
INSERT INTO bookIndex (address,name) VALUES ('/Users/glw/Downloads/众筹电子书/众筹电子书/第E9期（2018-12-10）','《一个64位操作系统的设计与实现》_田宇_2018-05-01.pdf');
INSERT INTO bookIndex (address,name) VALUES ('/Users/glw/Downloads/众筹电子书/众筹电子书/第E9期（2018-12-10）','《深度学习原理与实践》_陈仲铭等_2018-08-01.pdf');
INSERT INTO bookIndex (address,name) VALUES ('/Users/glw/Downloads/众筹电子书/众筹电子书/第E9期（2018-12-10）','《基于深度学习的自然语言处理》_车万翔等译_2018-05-01.pdf');
INSERT INTO bookIndex (address,name) VALUES ('/Users/glw/Downloads/众筹电子书/众筹电子书/第E9期（2018-12-10）','《Hive编程技术与应用》_孙帅等_2018-09-01.pdf');
INSERT INTO bookIndex (address,name) VALUES ('/Users/glw/Downloads/众筹电子书/众筹电子书/第E9期（2018-12-10）','《手把手教你设计CPU——RISC-V处理器篇》_胡振波_2018-05-01.pdf');
INSERT INTO bookIndex (address,name) VALUES ('/Users/glw/Downloads/众筹电子书/众筹电子书/第W期','《京东系统质量保障技术实战》.pdf');
INSERT INTO bookIndex (address,name) VALUES ('/Users/glw/Downloads/众筹电子书/众筹电子书/第W期','《京东平台数据化运营》.pdf');
INSERT INTO bookIndex (address,name) VALUES ('/Users/glw/Downloads/众筹电子书/众筹电子书/第C3期','《微服务设计原理与架构》.pdf');
INSERT INTO bookIndex (address,name) VALUES ('/Users/glw/Downloads/众筹电子书/众筹电子书/第G3期（2019-03-19）','《DevOps 最佳实践》_EXIN DevOps master译_2018-10-01.pdf');
INSERT INTO bookIndex (address,name) VALUES ('/Users/glw/Downloads/众筹电子书/众筹电子书/第T期','《可伸缩架构：面向增长应用的高可用》.pdf');
INSERT INTO bookIndex (address,name) VALUES ('/Users/glw/Downloads/众筹电子书/众筹电子书/第D6期（2018-09-11）','《深度学习：卷积神经网络从入门到精通》_张婷等.pdf');
INSERT INTO bookIndex (address,name) VALUES ('/Users/glw/Downloads/众筹电子书/众筹电子书/第D6期（2018-09-11）','《数据库事务处理的艺术：事务管理与并发控制》_李海翔.pdf');
INSERT INTO bookIndex (address,name) VALUES ('/Users/glw/Downloads/众筹电子书/众筹电子书/第A1期','《微信公众平台企业应用开发实战》.pdf');
INSERT INTO bookIndex (address,name) VALUES ('/Users/glw/Downloads/众筹电子书/众筹电子书/第A1期','《微信企业号开发完全自学手册》.pdf');
INSERT INTO bookIndex (address,name) VALUES ('/Users/glw/Downloads/众筹电子书/众筹电子书/第F7期（2019-02-05）','《Spring MVC+ MyBatis快速开发与项目实战》_黄文毅_2018-12-01.pdf');
INSERT INTO bookIndex (address,name) VALUES ('/Users/glw/Downloads/众筹电子书/众筹电子书/第F7期（2019-02-05）','《Java从小白到大牛》_关东升_2018-05-01.pdf');
INSERT INTO bookIndex (address,name) VALUES ('/Users/glw/Downloads/众筹电子书/众筹电子书/第D9期（2018-10-01国庆提前期）','《Keras深度学习实战》_王海玲等译.pdf');
INSERT INTO bookIndex (address,name) VALUES ('/Users/glw/Downloads/众筹电子书/众筹电子书/第C7期（2018-07-10）','《Java核心技术卷II：高级特性（原书第10版）》.pdf');
INSERT INTO bookIndex (address,name) VALUES ('/Users/glw/Downloads/众筹电子书/众筹电子书/第A2期','《实用机器学习》.pdf');
INSERT INTO bookIndex (address,name) VALUES ('/Users/glw/Downloads/众筹电子书/众筹电子书/第A2期','《精通Python自然语言处理》.pdf');
INSERT INTO bookIndex (address,name) VALUES ('/Users/glw/Downloads/众筹电子书/众筹电子书/第S期','《Python面向对象编程指南》.pdf');
INSERT INTO bookIndex (address,name) VALUES ('/Users/glw/Downloads/众筹电子书/众筹电子书/第Y期','《DB2从入门到精通（配光盘）（软件开发视频大讲堂）》.pdf');
INSERT INTO bookIndex (address,name) VALUES ('/Users/glw/Downloads/众筹电子书/众筹电子书/第A10期','《Docker实践》.pdf');
